### ISSUE TITLE
IBMiCmd not compatible with current version of Nodepad++

### ISSUE THREAD

**Issue by aaronbartell** [WorksOfBarry/IBMiCmd#26] opened 2017-07-27 21:45 UTC
Getting the following error when installing on Windows XP with Nodepad++ v7.4.2

![image](https://user-images.githubusercontent.com/106142/28693532-c26e2f36-72ea-11e7-9213-c8f20a0d64ad.png)

**Comment by ericjooka** [comment] 2017-07-27 21:48
If Microsoft no longer supports XP, why would Liam?

**Comment by WorksOfLiam** [comment] 2017-07-27 22:12
Hi @aaronbartell 

While it is pretty interesting that you're using Windows XP, are you using the 32bit version of Notepad++? If you launch Notepad++ and press F1, it will tell you if it's 64 or 32 bits.

I have just uploaded to 7.4.2 and it seems to load okay on the 32bit version.

If you'd like a 64 bit build, I can try make a copy for you.

Cheers,
Liam

**Comment by aaronbartell** [comment] 2017-07-28 12:37
>If Microsoft no longer supports XP, why would Liam?

Today I have enough on my plate with positioning the elastic on my belly.  Tomorrow I will see if XP [Aaron continues his drivel of complaining and eventually sequesters a bagel]


>I have just uploaded to 7.4.2 and it seems to load okay on the 32bit version.

I will move on from XP :-)  Below is from Windows 7 (same error).  What Windows version are you running?  
![image](https://user-images.githubusercontent.com/106142/28717353-0f93619c-7367-11e7-81b8-e19039a788ab.png)

Also, what's interesting is it lets me configure a server/profile/password successfully (which I am guessing is your code) but then eventually gives this error when I try to connect in the last step.

![image](https://user-images.githubusercontent.com/106142/28717480-91a62bc4-7367-11e7-8f4c-5b5681b5ac24.png)

**Comment by WorksOfLiam** [comment] 2017-07-28 12:44
Hi @aaronbartell 

The fact it lets you setup a profile and **then** gives you the issue is confusing. I am using Windows 10.

It should be noted that the at least .NET Framework 4.6.1 is required, you can [download the latest here](https://www.microsoft.com/en-us/download/details.aspx?id=55170&desc=dotnet47)

Are you able to see IBMiCmd in the Plugins dropdown when Notepad++ loads?

![image](https://user-images.githubusercontent.com/3708366/28717643-9158fbf0-739a-11e7-924b-0dfd5dcff107.png)

Are you able to use any of functions? The Member Listing is generally an easy one to try out.

Cheers,
Liam

**Comment by aaronbartell** [comment] 2017-07-28 13:11
After installing the v4.6.1 .NET Framework it is now working!  

I can now see all of the commands.

**Comment by WorksOfLiam** [comment] 2017-07-28 13:20
Excellent @aaronbartell!

I have also updated the wiki prerequisites accordingly, mentioning the version of the .NET Framework required.

Unless you have more questions, could you close the issue?

Thanks!

**Closed** 2017-07-28 13:33 UTC

**Comment by WPH-Erhard** [comment] 2017-09-21 17:31
I run my Client with WIN7-SP / 64 Bit + .NET Framework 4.7 and get the the above Windows "IBMiCmd.dll not compatible................"
I run Notepad++ Version 7.5.1. 

Greetings, Thomas
